"""Search criteria tree for advanced search"""


def load():
    return _DATA


_DATA = [
    {
        "children": [
            {"code": "233", "label": "1000"},
            {"code": "234", "label": "2000"},
            {"code": "235", "label": "3000"},
        ],
        "label": "Most frequent spoken words",
    },
    {
        "children": [
            {"code": "236", "label": "1000"},
            {"code": "237", "label": "2000"},
            {"code": "238", "label": "3000"},
        ],
        "label": "Most frequent written words",
    },
    {
        "children": [
            {"code": "332", "label": "Picture"},
            {"code": "333", "label": "Sound effect"},
        ],
        "label": "Multimedia",
    },
    {
        "children": [
            {"code": "334", "label": "adjective"},
            {"code": "335", "label": "adverb"},
            {"code": "336", "label": "auxiliary verb"},
            {"code": "337", "label": "conjunction"},
            {"code": "338", "label": "determiner"},
            {"code": "339", "label": "interjection"},
            {"code": "340", "label": "modal verb"},
            {
                "children": [{"code": "u1", "label": "uncountable"}],
                "code": "341",
                "label": "noun",
            },
            {"code": "342", "label": "number"},
            {"code": "343", "label": "phrasal verb"},
            {"code": "344", "label": "predeterminer"},
            {"code": "345", "label": "prefix"},
            {"code": "346", "label": "preposition"},
            {"code": "347", "label": "pronoun"},
            {"code": "348", "label": "suffix"},
            {"code": "349", "label": "verb"},
        ],
        "label": "Part of speech",
    },
    {
        "children": [
            {"code": "350", "label": "biblical"},
            {"code": "351", "label": "formal"},
            {"code": "352", "label": "humorous"},
            {"code": "353", "label": "informal"},
            {"code": "354", "label": "law"},
            {"code": "355", "label": "literary"},
            {"code": "356", "label": "medical"},
            {"code": "357", "label": "not polite"},
            {"code": "358", "label": "old use"},
            {"code": "359", "label": "old-fashioned"},
            {"code": "360", "label": "spoken"},
            {"code": "361", "label": "taboo"},
            {"code": "362", "label": "technical"},
            {"code": "363", "label": "trademark"},
            {"code": "364", "label": "written"},
        ],
        "label": "Register",
    },
    {
        "children": [
            {"code": "u2", "label": "British English"},
            {"code": "u3", "label": "American English"},
        ],
        "label": "Region",
    },
    {"code": "426", "label": "Academic Word List"},
    {
        "children": [
            {
                "children": [
                    {"code": "19", "label": "Architecture"},
                    {"code": "20", "label": "Literature"},
                    {
                        "children": [
                            {"code": "22", "label": "Film"},
                            {"code": "23", "label": "Television & Radio"},
                        ],
                        "code": "21",
                        "label": "Media",
                    },
                    {
                        "children": [
                            {"code": "25", "label": "Dance"},
                            {"code": "26", "label": "Music"},
                            {"code": "27", "label": "Theatre"},
                        ],
                        "code": "24",
                        "label": "Performing",
                    },
                    {
                        "children": [
                            {"code": "29", "label": "Design"},
                            {"code": "30", "label": "Painting and Drawing"},
                            {"code": "31", "label": "Sculpture"},
                        ],
                        "code": "28",
                        "label": "Visual",
                    },
                ],
                "code": "18",
                "label": "ARTS",
            },
            {
                "children": [
                    {
                        "children": [
                            {"code": "34", "label": "Advertising & Marketing"},
                            {"code": "35", "label": "Business Management"},
                            {"code": "36", "label": "Companies"},
                            {"code": "37", "label": "Offices"},
                            {"code": "38", "label": "Trade"},
                        ],
                        "code": "33",
                        "label": "Basics",
                    },
                    {
                        "children": [
                            {"code": "40", "label": "Conditions of Employment"},
                            {"code": "41", "label": "Labour Relations/Unions"},
                            {"code": "42", "label": "Wages"},
                        ],
                        "code": "39",
                        "label": "Employment",
                    },
                    {
                        "children": [
                            {"code": "44", "label": "Banking"},
                            {"code": "45", "label": "Insurance"},
                            {"code": "46", "label": "Loans"},
                            {"code": "47", "label": "Stocks & Shares"},
                        ],
                        "code": "43",
                        "label": "Finance",
                    },
                    {"code": "48", "label": "Occupations"},
                ],
                "code": "32",
                "label": "BUSINESS",
            },
            {
                "children": [
                    {"code": "50", "label": "Colours"},
                    {"code": "51", "label": "Shapes/Patterns"},
                    {"code": "52", "label": "Odours"},
                    {"code": "53", "label": "Textures/Sounds"},
                    {"code": "54", "label": "Tastes"},
                ],
                "code": "49",
                "label": "COLOURS & SOUNDS",
            },
            {
                "children": [
                    {
                        "children": [
                            {"code": "57", "label": "Hair & Beauty"},
                            {"code": "58", "label": "Clothes"},
                            {"code": "59", "label": "Jewellery"},
                        ],
                        "code": "56",
                        "label": "Clothes & Fashion",
                    },
                    {
                        "children": [
                            {"code": "61", "label": "Cooking"},
                            {"code": "62", "label": "Drink"},
                            {"code": "63", "label": "Food Dish"},
                            {"code": "64", "label": "Nutrition"},
                            {"code": "65", "label": "Tobacco"},
                            {"code": "66", "label": "Utensils"},
                        ],
                        "code": "60",
                        "label": "Food",
                    },
                    {
                        "children": [
                            {"code": "68", "label": "Board Games"},
                            {"code": "69", "label": "Cards"},
                            {"code": "70", "label": "Darts"},
                            {"code": "71", "label": "Gambling"},
                            {"code": "72", "label": "Other Games"},
                        ],
                        "code": "67",
                        "label": "Games",
                    },
                    {
                        "children": [
                            {"code": "74", "label": "Babies"},
                            {"code": "75", "label": "Cleaning"},
                            {"code": "76", "label": "Furniture"},
                            {"code": "77", "label": "House"},
                            {"code": "78", "label": "Pets"},
                            {"code": "79", "label": "Toys"},
                        ],
                        "code": "73",
                        "label": "Household",
                    },
                    {
                        "children": [
                            {"code": "81", "label": "Gardening"},
                            {"code": "82", "label": "Sewing & Knitting"},
                            {"code": "83", "label": "Outdoor"},
                            {"code": "84", "label": "Tourism"},
                        ],
                        "code": "80",
                        "label": "Leisure",
                    },
                    {"code": "85", "label": "Nature"},
                    {
                        "children": [
                            {"code": "87", "label": "American Football"},
                            {"code": "88", "label": "Baseball"},
                            {"code": "89", "label": "Cricket"},
                            {"code": "90", "label": "Football"},
                            {"code": "91", "label": "Golf"},
                            {"code": "92", "label": "Horses"},
                            {"code": "93", "label": "Other Sports"},
                            {"code": "94", "label": "Swimming"},
                            {"code": "95", "label": "Tennis"},
                        ],
                        "code": "86",
                        "label": "Sport",
                    },
                ],
                "code": "55",
                "label": "DAILY LIFE",
            },
            {
                "children": [
                    {"code": "97", "label": "Astronomy"},
                    {
                        "children": [
                            {"code": "99", "label": "Animals"},
                            {"code": "100", "label": "Birds"},
                            {"code": "101", "label": "Fish"},
                            {"code": "102", "label": "Human"},
                            {"code": "103", "label": "Insects"},
                            {"code": "104", "label": "Microbes/Genetics/Biochem"},
                            {"code": "105", "label": "Plants"},
                        ],
                        "code": "98",
                        "label": "Biology",
                    },
                    {
                        "children": [
                            {"code": "107", "label": "Compounds"},
                            {"code": "108", "label": "Elements"},
                            {"code": "109", "label": "Plastics"},
                        ],
                        "code": "106",
                        "label": "Chemistry",
                    },
                    {
                        "children": [
                            {"code": "111", "label": "Geology"},
                            {"code": "112", "label": "Meteorology"},
                            {"code": "113", "label": "Oceanography"},
                        ],
                        "code": "110",
                        "label": "Earth Sciences",
                    },
                    {
                        "children": [
                            {"code": "115", "label": "Numbers"},
                            {"code": "116", "label": "Statistics"},
                        ],
                        "code": "114",
                        "label": "Maths",
                    },
                    {
                        "children": [
                            {"code": "118", "label": "Electricity"},
                            {"code": "119", "label": "Optics"},
                        ],
                        "code": "117",
                        "label": "Physics",
                    },
                ],
                "code": "96",
                "label": "HARD SCIENCE",
            },
            {
                "children": [
                    {"code": "121", "label": "Alternative Medicine"},
                    {"code": "122", "label": "Birth"},
                    {
                        "children": [{"code": "124", "label": "Drug Culture"}],
                        "code": "123",
                        "label": "Drugs/Medicines",
                    },
                    {"code": "125", "label": "Hospital"},
                    {"code": "126", "label": "Illness & Disability"},
                    {"code": "127", "label": "Nurses, Doctors, etc"},
                    {"code": "128", "label": "Psychology/Psychiatry"},
                    {"code": "129", "label": "Death"},
                ],
                "code": "120",
                "label": "MEDICINE",
            },
            {
                "children": [
                    {
                        "children": [
                            {"code": "132", "label": "Currencies"},
                            {"code": "133", "label": "Tax"},
                            {"code": "134", "label": "Welfare"},
                        ],
                        "code": "131",
                        "label": "Economics",
                    },
                    {
                        "children": [
                            {"code": "136", "label": "Citizenship"},
                            {"code": "137", "label": "Officials"},
                            {"code": "138", "label": "Parliaments"},
                        ],
                        "code": "135",
                        "label": "Government",
                    },
                    {
                        "children": [
                            {"code": "140", "label": "Army"},
                            {"code": "141", "label": "Defence"},
                            {"code": "142", "label": "Navy"},
                            {"code": "143", "label": "Airforce"},
                            {"code": "144", "label": "Weapons"},
                        ],
                        "code": "139",
                        "label": "Military",
                    },
                    {
                        "children": [
                            {"code": "146", "label": "Groupings"},
                            {"code": "147", "label": "Policies"},
                            {"code": "148", "label": "Voting"},
                        ],
                        "code": "145",
                        "label": "Politics",
                    },
                ],
                "code": "130",
                "label": "POLITICS",
            },
            {
                "children": [
                    {"code": "150", "label": "Folklore"},
                    {"code": "151", "label": "Mythology"},
                    {
                        "children": [
                            {"code": "153", "label": "Astrology"},
                            {"code": "154", "label": "Magic"},
                        ],
                        "code": "152",
                        "label": "Occult",
                    },
                    {"code": "155", "label": "Philosophy"},
                    {
                        "children": [
                            {"code": "157", "label": "Buddhism"},
                            {"code": "158", "label": "Christianity"},
                            {"code": "159", "label": "Hinduism"},
                            {"code": "160", "label": "Islam"},
                            {"code": "161", "label": "Judaism"},
                        ],
                        "code": "156",
                        "label": "Religion",
                    },
                ],
                "code": "149",
                "label": "RELIGION & THOUGHT",
            },
            {
                "children": [
                    {
                        "children": [{"code": "164", "label": "Nationality & Race"}],
                        "code": "163",
                        "label": "Anthropology",
                    },
                    {
                        "children": [
                            {"code": "166", "label": "Bombs & Terrorism"},
                            {"code": "167", "label": "Crime"},
                            {"code": "168", "label": "Jail & punishment"},
                            {"code": "169", "label": "Law"},
                            {"code": "170", "label": "Police"},
                        ],
                        "code": "165",
                        "label": "Crime & Law",
                    },
                    {
                        "children": [
                            {"code": "172", "label": "College"},
                            {"code": "173", "label": "Pre School"},
                            {"code": "174", "label": "School"},
                            {"code": "175", "label": "Training"},
                        ],
                        "code": "171",
                        "label": "Education",
                    },
                    {
                        "children": [{"code": "177", "label": "Environment & waste"}],
                        "code": "176",
                        "label": "Geography",
                    },
                    {"code": "178", "label": "History"},
                    {
                        "children": [
                            {"code": "180", "label": "Letters & punctuation"},
                            {"code": "181", "label": "Grammar"},
                            {"code": "182", "label": "Languages"},
                        ],
                        "code": "179",
                        "label": "Linguistics",
                    },
                    {
                        "children": [
                            {"code": "184", "label": "Children"},
                            {"code": "185", "label": "Family"},
                            {"code": "186", "label": "Organizations"},
                            {"code": "187", "label": "Race Relations"},
                            {"code": "188", "label": "Women"},
                            {"code": "189", "label": "Youth"},
                        ],
                        "code": "183",
                        "label": "Sociology",
                    },
                    {"code": "190", "label": "Archaeology"},
                ],
                "code": "162",
                "label": "SOCIETY",
            },
            {
                "children": [
                    {
                        "children": [
                            {"code": "193", "label": "Crops"},
                            {"code": "194", "label": "Forestry"},
                            {"code": "195", "label": "Soil"},
                        ],
                        "code": "192",
                        "label": "Agriculture",
                    },
                    {
                        "children": [
                            {"code": "197", "label": "Buildings"},
                            {"code": "198", "label": "Construction"},
                        ],
                        "code": "196",
                        "label": "Building",
                    },
                    {
                        "children": [
                            {"code": "200", "label": "Broadcasting"},
                            {"code": "201", "label": "Mail"},
                            {
                                "code": "202",
                                "label": "Newspapers/Printing/Publishing",
                            },
                            {"code": "203", "label": "Photography"},
                            {"code": "204", "label": "Recording"},
                            {"code": "205", "label": "Telephone/Telegraph"},
                        ],
                        "code": "199",
                        "label": "Communications",
                    },
                    {"code": "206", "label": "Computers"},
                    {
                        "children": [
                            {"code": "208", "label": "Civil"},
                            {"code": "209", "label": "Electrical"},
                            {"code": "210", "label": "Mechanical"},
                        ],
                        "code": "207",
                        "label": "Engineering",
                    },
                    {
                        "children": [
                            {"code": "212", "label": "Crafts"},
                            {"code": "213", "label": "Factories"},
                            {"code": "214", "label": "Glass"},
                            {"code": "215", "label": "Material & Textiles"},
                            {"code": "216", "label": "Pottery & Ceramics"},
                        ],
                        "code": "211",
                        "label": "Industry",
                    },
                    {
                        "children": [
                            {"code": "218", "label": "Chronology"},
                            {"code": "219", "label": "Temperature"},
                        ],
                        "code": "217",
                        "label": "Measurement",
                    },
                    {
                        "children": [
                            {"code": "221", "label": "Electricity"},
                            {"code": "222", "label": "Gas/Coal/Oil"},
                            {"code": "223", "label": "Wind/Water/Sun"},
                        ],
                        "code": "220",
                        "label": "Power",
                    },
                    {
                        "children": [
                            {"code": "225", "label": "Air"},
                            {"code": "226", "label": "Bicycles/Carts/Horses"},
                            {"code": "227", "label": "Motor Vehicles"},
                            {"code": "228", "label": "Roads"},
                            {"code": "229", "label": "Space"},
                            {"code": "230", "label": "Trains & Railways"},
                            {"code": "231", "label": "Water"},
                        ],
                        "code": "224",
                        "label": "Transport",
                    },
                    {"code": "232", "label": "Tools"},
                ],
                "code": "191",
                "label": "TECHNOLOGY",
            },
        ],
        "label": "Subject",
    },
    {
        "children": [
            {
                "children": [
                    {"code": "368", "label": "architects, designers"},
                    {"code": "369", "label": "artists"},
                    {"code": "370", "label": "business"},
                    {"code": "371", "label": "cinema, TV"},
                    {"code": "372", "label": "crime"},
                    {"code": "373", "label": "dancers"},
                    {"code": "374", "label": "economy, finance"},
                    {"code": "375", "label": "educators"},
                    {"code": "376", "label": "engineers, inventors"},
                    {"code": "377", "label": "explorers, navigators"},
                    {"code": "378", "label": "fashion"},
                    {"code": "379", "label": "heroes"},
                    {"code": "380", "label": "lawyers, judges"},
                    {"code": "381", "label": "writers"},
                    {"code": "382", "label": "medical"},
                    {"code": "383", "label": "military"},
                    {"code": "384", "label": "music"},
                    {"code": "385", "label": "philosophers"},
                    {"code": "386", "label": "political"},
                    {"code": "387", "label": "religious"},
                    {"code": "388", "label": "royal"},
                    {"code": "389", "label": "scientists"},
                    {"code": "390", "label": "social reformers"},
                    {"code": "391", "label": "sports"},
                ],
                "code": "365",
                "label": "People",
            },
            {
                "children": [
                    {"code": "392", "label": "city"},
                    {"code": "393", "label": "country"},
                    {"code": "394", "label": "feature"},
                    {"code": "395", "label": "region"},
                    {"code": "396", "label": "site"},
                ],
                "code": "366",
                "label": "Places",
            },
            {
                "children": [
                    {"code": "397", "label": "arts, architecture"},
                    {"code": "398", "label": "business,commerce"},
                    {"code": "399", "label": "calendar"},
                    {"code": "400", "label": "ceremonies, traditions"},
                    {"code": "401", "label": "cinema, TV"},
                    {"code": "402", "label": "consumer goods"},
                    {"code": "403", "label": "crime"},
                    {"code": "404", "label": "dance companies"},
                    {"code": "405", "label": "economy, finance"},
                    {"code": "406", "label": "education"},
                    {"code": "407", "label": "environmental"},
                    {"code": "408", "label": "fiction"},
                    {"code": "409", "label": "geographical"},
                    {"code": "410", "label": "history"},
                    {"code": "411", "label": "law"},
                    {"code": "412", "label": "literature"},
                    {"code": "413", "label": "medical"},
                    {"code": "414", "label": "military"},
                    {"code": "415", "label": "musical"},
                    {"code": "416", "label": "mythological names"},
                    {"code": "418", "label": "politics"},
                    {"code": "419", "label": "religious"},
                    {"code": "420", "label": "science"},
                    {"code": "421", "label": "social"},
                    {"code": "422", "label": "sports"},
                    {"code": "423", "label": "theatre"},
                    {"code": "424", "label": "transport"},
                ],
                "code": "367",
                "label": "Other",
            },
        ],
        "label": "Culture",
    },
    {
        "children": [
            {"code": "5", "label": "8th century"},
            {"code": "6", "label": "9th century"},
            {"code": "7", "label": "10th century"},
            {"code": "8", "label": "11th century"},
            {"code": "9", "label": "12th century"},
            {"code": "10", "label": "13th century"},
            {"code": "11", "label": "14th century"},
            {"code": "12", "label": "15th century"},
            {"code": "13", "label": "16th century"},
            {"code": "14", "label": "17th century"},
            {"code": "15", "label": "18th century"},
            {"code": "16", "label": "19th century"},
            {"code": "17", "label": "20th century"},
        ],
        "label": "Date",
    },
    {
        "children": [
            {"code": "239", "label": "Afrikaans"},
            {"code": "240", "label": "Aleut"},
            {"code": "241", "label": "Algonquian"},
            {"code": "242", "label": "American Spanish"},
            {"code": "243", "label": "Anglo-French"},
            {"code": "244", "label": "Arabic"},
            {"code": "245", "label": "Aramaic"},
            {"code": "246", "label": "Arawakan"},
            {"code": "247", "label": "Australian Aboriginal"},
            {"code": "248", "label": "Aymara"},
            {"code": "249", "label": "Bantu"},
            {"code": "250", "label": "Canadian French"},
            {"code": "251", "label": "Carib"},
            {"code": "252", "label": "Catalan"},
            {"code": "253", "label": "Celtic"},
            {"code": "254", "label": "Chinese"},
            {"code": "255", "label": "Czech"},
            {"code": "256", "label": "Danish"},
            {"code": "257", "label": "Dharuk"},
            {"code": "258", "label": "Dutch"},
            {"code": "259", "label": "Egyptian"},
            {"code": "260", "label": "English"},
            {"code": "261", "label": "English dialect"},
            {"code": "262", "label": "Flemish"},
            {"code": "263", "label": "French"},
            {"code": "264", "label": "French dialect"},
            {"code": "265", "label": "German"},
            {"code": "266", "label": "German dialect"},
            {"code": "267", "label": "Germanic"},
            {"code": "268", "label": "Greek"},
            {"code": "269", "label": "Hawaiian"},
            {"code": "270", "label": "Hebrew"},
            {"code": "271", "label": "Hindi"},
            {"code": "272", "label": "Hungarian"},
            {"code": "273", "label": "Icelandic"},
            {"code": "274", "label": "Irish Gaelic"},
            {"code": "275", "label": "Italian"},
            {"code": "276", "label": "Italian dialect"},
            {"code": "277", "label": "Japanese"},
            {"code": "278", "label": "Korean"},
            {"code": "279", "label": "Late Greek"},
            {"code": "280", "label": "Late Latin"},
            {"code": "281", "label": "Latin"},
            {"code": "282", "label": "Louisiana French"},
            {"code": "283", "label": "Low German"},
            {"code": "284", "label": "Malay"},
            {"code": "285", "label": "Maori"},
            {"code": "286", "label": "Medieval Greek"},
            {"code": "287", "label": "Medieval Latin"},
            {"code": "288", "label": "Mexican Spanish"},
            {"code": "289", "label": "Middle Dutch"},
            {"code": "290", "label": "Middle High German"},
            {"code": "291", "label": "Middle Low German"},
            {"code": "292", "label": "Modern Greek"},
            {"code": "293", "label": "Modern Latin"},
            {"code": "294", "label": "Nahuatl"},
            {"code": "295", "label": "Narragansett"},
            {"code": "296", "label": "Norwegian"},
            {"code": "297", "label": "Ojibwa"},
            {"code": "298", "label": "Old English"},
            {"code": "299", "label": "Old French"},
            {"code": "300", "label": "Old Irish"},
            {"code": "301", "label": "Old Italian"},
            {"code": "302", "label": "Old Norse"},
            {"code": "303", "label": "Old North French"},
            {"code": "304", "label": "Old Proven\xe7al"},
            {"code": "305", "label": "Old Spanish"},
            {"code": "306", "label": "Persian"},
            {"code": "307", "label": "Pidgin English"},
            {"code": "308", "label": "Polish"},
            {"code": "309", "label": "Portuguese"},
            {"code": "310", "label": "Proven\xe7al"},
            {"code": "311", "label": "Quechua"},
            {"code": "312", "label": "Romany"},
            {"code": "313", "label": "Russian"},
            {"code": "314", "label": "Sanskrit"},
            {"code": "315", "label": "Scandinavian"},
            {"code": "316", "label": "Scottish English"},
            {"code": "317", "label": "Scottish Gaelic"},
            {"code": "318", "label": "Spanish"},
            {"code": "319", "label": "Swedish"},
            {"code": "320", "label": "Taino"},
            {"code": "321", "label": "Tamil"},
            {"code": "322", "label": "Tibetan"},
            {"code": "323", "label": "Tupi"},
            {"code": "324", "label": "Turkish"},
            {"code": "325", "label": "Urdu"},
            {"code": "326", "label": "Virginia Algonquian"},
            {"code": "327", "label": "Vulgar Latin"},
            {"code": "328", "label": "Welsh"},
            {"code": "329", "label": "West African"},
            {"code": "330", "label": "Yiddish"},
            {"code": "331", "label": "Zulu"},
        ],
        "label": "Language of origin",
    },
]
